### ISSUE TITLE
2.7.0 arm64 version missing as downloadable asset

### ISSUE THREAD

**Issue by ivanbacher** [Martin8617/Defi-Node-for-Raspberry-Pi#1]
Hi, 

Thank you for doing this. The downloadable 2.7.0 arm64 version seems to be missing from the [releases page](https://github.com/Martin8617/Defi-Node-for-Raspberry-Pi/releases/tag/V2.7.0).

**Comment by Martin8617** [comment]
It's missing because I have problems to compile the source code. I do my best to release it bevore 11th April.
I have opend an issue (https://github.com/DeFiCh/ain/issues/1187) at Defichain.

**Comment by ivanbacher** [comment]
Awesome. Thank you very much

**Comment by ivanbacher** [comment]
I was able to build the executable by adding this flag: `march=armv8-a+crc+crypto`

So the new `./config` command would be:

```
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" CXXFLAGS="-march=armv8-a+crc+crypto" --prefix=$PWD/depends/aarch64-linux-gnu --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++
```

Honestly, I don't really know why it works now. Just tried a couple of things. A complete list of flags can be found here: https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

**Comment by Martin8617** [comment]
Hey Ivan
Du bist mein Hero!
Das Flag so zu nutzen ist die Lösung. Im Verlauf von `./configure` hatte ich die  beiden Zeilen:
```
checking whether C++ compiler accepts -march=armv8-a+crc+crypto... yes
checking for AArch64 CRC32 intrinsics... no
```
...und das `intrinsics` musste auf "yes"
Ich habe in den crc32c-files rumprobiert, aber kam noch nicht zum Erfolg; nun flutsch's :D 
Ich danke dir vielmals.
